# Generated by Django 3.2.15 on 2024-05-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='timezone',
        ),
    ]
