# Generated by Django 3.2.15 on 2024-05-11 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_auto_20240511_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_flight', to='airline.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='outboud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_flight', to='airline.airport'),
        ),
    ]
