# Generated by Django 3.2.15 on 2024-05-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_remove_airport_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='unique_code',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
