# Generated by Django 3.2.15 on 2024-05-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_auto_20240511_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='flights',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Miss', 'Miss'), ('Ms', 'Ms.')], default='Mr', max_length=4),
            preserve_default=False,
        ),
    ]
