# Generated by Django 3.2.15 on 2024-05-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_auto_20240513_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms')], max_length=4),
        ),
    ]
