# Generated by Django 3.2.15 on 2024-05-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0005_alter_customuser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
