# Generated by Django 3.2.15 on 2024-05-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0006_auto_20240513_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.CharField(default='New Zealand', max_length=128),
            preserve_default=False,
        ),
    ]
