# Generated by Django 3.2.15 on 2024-05-14 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0008_customuser_flights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='outboud',
            new_name='outbound',
        ),
    ]
