# Generated by Django 3.2.15 on 2024-05-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0009_rename_outboud_flight_outbound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
