# Generated by Django 3.2.15 on 2024-05-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0010_alter_flight_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
